language: node_js
node_js:
  - 6.5.0
before_install:
  - rvm install 2.3.1
before_script:
- chmod +x ./cibuild.sh
script: "./cibuild.sh"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
addons:
  ssh_known_hosts: $hostname
before_install:
- openssl aes-256-cbc -K $encrypted_4395499fa958_key -iv $encrypted_4395499fa958_iv
  -in dash.org-test-web.pem.enc -out dash.org-test-web.pem -d
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/$IdentityFile
- ssh-add $TRAVIS_BUILD_DIR/$IdentityFile
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/_dist $user@$hostname:$production_path
  on:
    branch: master
