language: node_js
node_js:
- 4.5.0
before_script:
- chmod +x ./cibuild.sh
- ssh-keyscan -H -t rsa,dsa $hostname >> ~/.ssh/known_hosts
script: ./cibuild.sh
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - CXX=g++-4.8
sudo: false
addons:
  ssh_known_hosts:
  - www-test.dash.org
  - 146.185.153.42
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- rvm install 2.3.1
deploy:
  provider: script
  skip_cleanup: true
  script: test $TRAVIS_TEST_RESULT = 0 && script/deploy-rsync.sh
  on:
    all_branches: true
